### PR TITLE
Update documentation to explain feature flag usage

### PR DESCRIPTION
**Pull request by codecog**
This change adds further explanation as to how to switch to a different variant of the v8 package.

### CODE REVIEW

**Comment by Kudo** [comment]
Hey @codecog, thank you so much for helping me to update the missing document.
There is just a nit. Do you mind to keep some v8-android-nointl description?
There are four variants existed in fact:

- v8-android
- v8-android-nointl
- v8-android-jit
- v8-android-jit-nointl

It would be great to mention these four variants in the README.
Thank you.

**Comment by codecog** [comment]
No problem, will update the pr today

**Comment by Kudo** [comment]
Take your time and thank you very much.

**Comment by codecog** [comment]
@Kudo Let me know if you think it needs any further explanation

**Comment by Kudo** [comment]
Looks great and thank you so much.
I am getting to merge this.

**Pull request merged**
