### PR TITLE
feat: add react-native 0.74 support

### PR DESCRIPTION
**Pull request by Kudo**
# Why

add react native 0.74 and expo sdk 51 support

# How

- [v8runtime] add stub `setExternalMemoryPressure()`
- [android] fix build error on 0.74
- [ios] update config-plugin to support 0.74 from RCTRootViewFactory
- [ci] update test for react-native 0.74 and expo sdk 51

### CODE REVIEW

**Comment by reinismu** [comment]
Thank you @Kudo :100: 

When do you plan to make new release?

**Comment by Kudo** [comment]
@reinismu `react-native-v8@2.4.0` published. sorry for long wait

**Comment by Kudo** [comment]
oh no, wait 0.74.3 has a new interface to jsi and breaks my previous work. will create a pr to fix that soon

**Comment by Kudo** [comment]
`react-native-v8@2.5.0` should work.

**Pull request merged**
